---
 - name:  Configure EC2 instances using Ansible
   hosts: webservers
   become: true
   gather_facts: False
   
   tasks:
     - name: Update apt-get repo and cache
       apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
     - name: Upgrade all apt packages
       apt: upgrade=dist force_apt_get=yes
     - name: Install Pre-requisites
       apt: 
         pkg:
           - php
           - python  
         state: latest
         update_cache: true
