apiVersion: batch/v1
kind: Job
metadata:
  name: node-poc-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - date; echo "Starting Job";  ansible --version; ansible-playbook create_ec2.yml --extra-vars "AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_SECRET_KEY=$AWS_SECRET_KEY"; chmod 600 /app/devops/devops-poc.pem; export awsIP=`sed -n '2 p' ansible.inv`; mkdir ~/.ssh ; ssh-keyscan -H $awsIP >> ~/.ssh/known_hosts; scp -i /app/devops/devops-poc.pem -r /app ubuntu@$awsIP:/tmp ; ansible-playbook ec2-configure.yml -i ansible.inv; echo "Finished"; exit 0
        name: node-poc
        image: $imageName
        envFrom:
        - secretRef:
            name: kt-aws-creds
        volumeMounts:
        - name: "aws-key"
          mountPath: "/app/devops/devops-poc.pem"
          subPath: "devops-poc.pem"
          readOnly: true        

      imagePullSecrets:
      # kubernetes secret created for docker registry
      - name: afour-private-registry-creds
      restartPolicy: Never
      volumes:
        - name: "aws-key"
          secret:
            defaultMode: 420
            secretName: "kt-aws-creds"
