apiVersion: batch/v1
kind: Job
metadata:
  name: node-poc-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - date; echo "Starting CronJob"; ansible --version; ansible-playbook create_ec2.yml --extra-vars "AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_SECRET_KEY=$AWS_SECRET_KEY"; echo "Finished"; exit 0
        image: $imageName
        envFrom:
        - secretRef:
            name: kt-aws-creds
        imagePullPolicy: Always
        name: node-poc-job
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: afour-private-registry-creds
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
